title: Hoe Sung Ryu
url: "https://github.com/hoesungryu"
baseurl: ""

markdown: kramdown
ins_logo: "./yonsei_korea_.jpg"

tracking_id: UA-138665784-2 #


footer: no
footer_url: "https://github.com/hoesungryu"
footer_text: "Hoe Sung Ryu"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
#    link: ""
#  - name: "CV"
#    link: ""
#  - name: "Blog"
#    link: "https://minsuksung-ai.tistory.com/"
#  - name: "Facebook"
#    link: "https://www.facebook.com/"

remote_theme: ankitsultana/researcher@gem

theme: jekyll-theme-cayman
